#!/usr/bin/env bash
# cleanup.sh — targeted disk cleanup for the GA36-MB V1.2 (A33) project.
# Safe, idempotent, keeps all forensic evidence and reproducibility inputs.
#
# Removes:
#   1. Previous-agent scratch scripts in the opencode temp dir.
#   2. Kernel/BusyBox build caches ($FW_WORK/build, $FW_WORK/src).
#   3. Old images in output/firmware/ (the *.img and boot/ payload, regenerated by build.sh).
#
# Keeps (never touched):
#   original/test.img, board/, scripts/, configs/, docs/, extract/, output/*.fex|*.dts|*.md,
#   work/vendor-lcd (lcd.ko), work/squash, work/{k1,k2,kernel}* dumps,
#   $FW_WORK/dl (download cache — offline reproducibility), $FW_WORK/toolchain.
#
# Usage: ./cleanup.sh   (run from WSL or any bash on this machine)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Resolve the build work area exactly like scripts/fw/env.sh -------------------------
FW_WORK="${GA36_FW_WORK:-}"
if [ -z "$FW_WORK" ] && [ -n "${WSL_DISTRO_NAME:-}" ]; then
    FW_WORK="$HOME/r36s-fw-work"
fi
if [ -z "$FW_WORK" ]; then
    FW_WORK="$ROOT/work"
fi

# --- Resolve the opencode temp dir (portable) ------------------------------------------
if [ -n "${TMPDIR:-}" ] && [ -d "$TMPDIR/opencode" ]; then
    OPENCODE_TMP="$TMPDIR/opencode"
elif [ -n "${LOCALAPPDATA:-}" ] && [ -d "$LOCALAPPDATA/Temp/opencode" ]; then
    OPENCODE_TMP="$LOCALAPPDATA/Temp/opencode"
elif [ -d "/tmp/opencode" ]; then
    OPENCODE_TMP="/tmp/opencode"
else
    OPENCODE_TMP=""
fi

echo "==> 1/4 Previous-agent scratch in temp opencode"
if [ -n "$OPENCODE_TMP" ] && [ -d "$OPENCODE_TMP" ]; then
    find "$OPENCODE_TMP" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
    echo "    cleared: $OPENCODE_TMP"
else
    echo "    skip (not found)"
fi

echo "==> 2/4 Kernel/BusyBox build caches"
for d in "$FW_WORK/build" "$FW_WORK/src"; do
    if [ -d "$d" ]; then
        rm -rf "$d"
        echo "    removed: $d"
    else
        echo "    skip (missing): $d"
    fi
done
echo "    kept:  $FW_WORK/dl (download cache), $FW_WORK/toolchain"

echo "==> 3/4 Old images in output/firmware (build scripts stay in scripts/fw/)"
if [ -d "$ROOT/output/firmware/boot" ]; then
    rm -rf "$ROOT/output/firmware/boot"
    echo "    removed: output/firmware/boot"
else
    echo "    skip (missing): output/firmware/boot"
fi
for f in "$ROOT/output/firmware/"*.img "$ROOT/output/firmware/"*.raw; do
    [ -e "$f" ] || continue
    rm -f "$f"
    echo "    removed: ${f#"$ROOT/"}"
done

echo ""
echo "Done. Next: ./build.sh regenerates output/firmware/ga36-stockboot.img."
